# # A pipe that executes repository information to SonarCloud [https://sonarcloud.io]

# name: pylint

# on:
#   push:
#   pull_request:
#     types: [opened, synchronize, reopened]
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#       with:
#         submodules: recursive
#         fetch-depth: 0

#     - name: Set up Python 3.9
#       uses: actions/setup-python@v3
#       with:
#         python-version: 3.9

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pylint pytest pytest-cov selenium playwright

#     - name: SonarCloud Scan
#       uses: SonarSource/sonarcloud-github-action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


name: Analyse SonarCloud

on:
  push:
    branches:
    - "master"
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
#       - uses: actions/checkout@v3
#         with:
#           submodules: recursive
#           fetch-depth: 0

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         with:
#           args: |
#             -Dsonar.projectKey=republique-et-canton-de-geneve_noms-geographiques
#             -Dsonar.organization=etat-de-geneve-github
      - name: List dir
        run: |
              ls -a
      - name: Where am I
        run: |
              pwd
